image: continuumio/anaconda3:latest

stages:
  - build

build:
  stage: build
  before_script:
    - conda create -n sciQt python=3.7
    - source activate sciQt
  script:
  - apt-get install -y python-dev python-pip
  - python setup.py install
  - pytest
