dist: xenial
# services:
#   - xvfb
language: python
python:
  - "3.7"

# sudo: required

addons:
  apt:
    packages:
    - libxkbcommon-x11-0

# before_install:
#   - sudo apt-get update
#   - sudo apt-get install -y xvfb herbstluftwm

install:
  - pip install -r requirements.txt
  # - pip install .
  - python setup.py install

# before_script:
#   - "herbstluftwm &"
#   - sleep 1

script:
  # - pytest -s -v
  - xvfb-run -a pytest -s -v
