sudo: required

dist: xenial
services:
  - xvfb

language: python
python:
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb herbstluftwm

install:
  - pip install -r requirements.txt
  - pip install .

before_script:
  - "herbstluftwm &"
  - sleep 1

script:
  - pytest
