dist: xenial

language: python
python:
  - "3.7"

addons:
  apt:
    packages:
    - libxkbcommon-x11-0

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - xvfb-run -a pytest -s -v
